extends: airbnb-base
plugins:
  - import
  - ava
parserOptions: 
  sourceType: script

rules:
  comma-dangle:
    - error
    - never
  import/no-extraneous-dependencies:
    - error
    - devDependencies: ['**/test.js']
